project:
  type: website
  output-dir: docs

website:
  title: "Alden Kling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu: 
         - text: "March Madness"
           href: MarchMadness.html
         - text: "Education in English Towns"
           href: EnglishEd.html
         - text: "Dickinson's Poems"
           href: DickinsonPoems.html
         - text: "Does American Airlines Suck?"
           href: AmAirSucks.html
         - text: "Investigation of Mean Absorbance"
           href: MeanAbsorbance.html
         - text: "Word Cloud Presentation"
           href: Slides.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



