project:
  type: website
  output-dir: docs

website:
  title: "Alden Kling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu: 
         - text: "March Madness"
           href: MarchMadness.html
         - text: "Education in English Towns"
           href: EnglishEd.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



