project:
  type: website
  output-dir: docs

website:
  title: "Alden Kling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - TidyTuesday.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



